In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[7675, 4014, 7926, 3952],
 [7675, 4014, 7926, 9660],
 [7675, 2655, 7926, 9458],
 [8896, 8859, 9856, 7389, 7251],
 [8896, 8859, 9856, 7389, 506],
 [7961, 7675, 2796, 7926, 3423],
 [8753, 7274, 8260, 7389]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7675 4014 7926 3952]
 [   0    0    0    0 7675 4014 7926 9660]
 [   0    0    0    0 7675 2655 7926 9458]
 [   0    0    0 8896 8859 9856 7389 7251]
 [   0    0    0 8896 8859 9856 7389  506]
 [   0    0    0 7961 7675 2796 7926 3423]
 [   0    0    0    0 8753 7274 8260 7389]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 148ms/step


array([[[-0.02527461, -0.04088608,  0.02789206, -0.01046717,
         -0.04787376, -0.01668655, -0.02814257, -0.00742016,
          0.03289788,  0.02771692],
        [-0.02527461, -0.04088608,  0.02789206, -0.01046717,
         -0.04787376, -0.01668655, -0.02814257, -0.00742016,
          0.03289788,  0.02771692],
        [-0.02527461, -0.04088608,  0.02789206, -0.01046717,
         -0.04787376, -0.01668655, -0.02814257, -0.00742016,
          0.03289788,  0.02771692],
        [-0.02527461, -0.04088608,  0.02789206, -0.01046717,
         -0.04787376, -0.01668655, -0.02814257, -0.00742016,
          0.03289788,  0.02771692],
        [-0.01316987,  0.03371787,  0.03292277, -0.01522465,
         -0.02103434, -0.03779532,  0.02658227,  0.03117344,
         -0.00968537, -0.0425185 ],
        [ 0.01320999,  0.02105618,  0.00598101, -0.04925826,
          0.0108526 ,  0.01896778,  0.01410386, -0.01192044,
          0.02782544, -0.00271121],
        [ 0.02131603,  0.04834843, -0.02470841, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7675, 4014, 7926, 3952])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 44ms/step


array([[-0.02527461, -0.04088608,  0.02789206, -0.01046717, -0.04787376,
        -0.01668655, -0.02814257, -0.00742016,  0.03289788,  0.02771692],
       [-0.02527461, -0.04088608,  0.02789206, -0.01046717, -0.04787376,
        -0.01668655, -0.02814257, -0.00742016,  0.03289788,  0.02771692],
       [-0.02527461, -0.04088608,  0.02789206, -0.01046717, -0.04787376,
        -0.01668655, -0.02814257, -0.00742016,  0.03289788,  0.02771692],
       [-0.02527461, -0.04088608,  0.02789206, -0.01046717, -0.04787376,
        -0.01668655, -0.02814257, -0.00742016,  0.03289788,  0.02771692],
       [-0.01316987,  0.03371787,  0.03292277, -0.01522465, -0.02103434,
        -0.03779532,  0.02658227,  0.03117344, -0.00968537, -0.0425185 ],
       [ 0.01320999,  0.02105618,  0.00598101, -0.04925826,  0.0108526 ,
         0.01896778,  0.01410386, -0.01192044,  0.02782544, -0.00271121],
       [ 0.02131603,  0.04834843, -0.02470841, -0.00534518, -0.02545782,
        -0.00583347, -0.00374129, -0.01123804